name: Build APK Quest 3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Android SDK 34
        run: yes | sdkmanager --sdk_root=/usr/lib/android-sdk "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Create build directory
        run: mkdir -p build

      - name: Build Quest APK
        env:
          HOME: /root
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_HOME: /usr/lib/android-sdk
        run: godot --headless --verbose --path . --export-debug "Quest 3" build/tibo-narvalo.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tibo-Narvalo-Quest3
          path: build/tibo-narvalo.apk
          if-no-files-found: error
